[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "master-thesis-uq-churn"
version = "0.0.0"
requires-python = ">=3.10"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["thesis_uq", "pytorch_tabnet"]
